"""table disrib2

Revision ID: 01557b77c8d8
Revises: 408013666e94
Create Date: 2019-06-16 21:25:14.150136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01557b77c8d8'
down_revision = '408013666e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_type', sa.String(length=64), nullable=False),
    sa.Column('req_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_type')
    )
    op.drop_table('requirements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('req_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('req_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='requirements_pkey'),
    sa.UniqueConstraint('req_type', name='requirements_req_type_key')
    )
    op.drop_table('requirement')
    # ### end Alembic commands ###
