"""gem table

Revision ID: 13945cbac71d
Revises: 13c9f8d6f91d
Create Date: 2019-05-25 14:32:29.283154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13945cbac71d'
down_revision = '13c9f8d6f91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomination', sa.Column('elf_id', sa.Integer(), nullable=True))
    op.add_column('nomination', sa.Column('gem_id', sa.Integer(), nullable=True))
    op.add_column('nomination', sa.Column('master_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nomination', 'user', ['elf_id'], ['id'])
    op.create_foreign_key(None, 'nomination', 'gem', ['gem_id'], ['id'])
    op.create_foreign_key(None, 'nomination', 'user', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nomination', type_='foreignkey')
    op.drop_constraint(None, 'nomination', type_='foreignkey')
    op.drop_constraint(None, 'nomination', type_='foreignkey')
    op.drop_column('nomination', 'master_id')
    op.drop_column('nomination', 'gem_id')
    op.drop_column('nomination', 'elf_id')
    # ### end Alembic commands ###
