"""gem table

Revision ID: 13c9f8d6f91d
Revises: 6715d7f7490a
Create Date: 2019-05-19 11:54:33.452208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c9f8d6f91d'
down_revision = '6715d7f7490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('elf_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gem', 'user', ['elf_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.drop_column('gem', 'elf_id')
    # ### end Alembic commands ###
