"""table 30

Revision ID: 16808d07d765
Revises: b2b8a3d9e364
Create Date: 2019-05-30 19:31:45.139039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16808d07d765'
down_revision = 'b2b8a3d9e364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('assigned_type', sa.String(length=64), nullable=True))
    op.add_column('gem', sa.Column('confirmed_date', sa.DateTime(), nullable=True))
    op.drop_column('gem', 'nomination_type')
    op.drop_column('gem', 'nomination_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('nomination_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('gem', sa.Column('nomination_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('gem', 'confirmed_date')
    op.drop_column('gem', 'assigned_type')
    # ### end Alembic commands ###
