"""users table

Revision ID: 2cae09646e94
Revises: 7b4e2abfd900
Create Date: 2019-05-11 19:09:25.142818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cae09646e94'
down_revision = '7b4e2abfd900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preference', 'elf_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('preference', 'elf_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
