"""table disrib

Revision ID: 408013666e94
Revises: 98a21f1636c5
Create Date: 2019-06-16 21:03:32.060309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408013666e94'
down_revision = '98a21f1636c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_type', sa.String(length=64), nullable=False),
    sa.Column('req_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    # ### end Alembic commands ###
