"""gem table

Revision ID: 6715d7f7490a
Revises: bd86216f4e63
Create Date: 2019-05-19 11:30:08.550629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6715d7f7490a'
down_revision = 'bd86216f4e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gem_elf_id_fkey', 'gem', type_='foreignkey')
    op.drop_column('gem', 'elf_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('elf_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gem_elf_id_fkey', 'gem', 'user', ['elf_id'], ['id'])
    # ### end Alembic commands ###
