"""table 30

Revision ID: 98a21f1636c5
Revises: c32f046edd17
Create Date: 2019-06-01 16:33:22.423907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a21f1636c5'
down_revision = 'c32f046edd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'type_gem', ['type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_gem', type_='unique')
    # ### end Alembic commands ###
