"""gem table

Revision ID: bd86216f4e63
Revises: 2cae09646e94
Create Date: 2019-05-19 11:26:24.980730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd86216f4e63'
down_revision = '2cae09646e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('elf_id', sa.Integer(), nullable=True))
    op.add_column('gem', sa.Column('gnome_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gem', 'user', ['elf_id'], ['id'])
    op.create_foreign_key(None, 'gem', 'user', ['gnome_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.drop_column('gem', 'gnome_id')
    op.drop_column('gem', 'elf_id')
    # ### end Alembic commands ###
