"""table 30

Revision ID: c31ca2a85ceb
Revises: 16808d07d765
Create Date: 2019-05-30 19:40:48.835460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c31ca2a85ceb'
down_revision = '16808d07d765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('confirmation_date', sa.DateTime(), nullable=True))
    op.drop_column('gem', 'confirmed_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('confirmed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('gem', 'confirmation_date')
    # ### end Alembic commands ###
