"""table 30

Revision ID: c32f046edd17
Revises: c31ca2a85ceb
Create Date: 2019-05-30 20:11:54.774861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32f046edd17'
down_revision = 'c31ca2a85ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('assignation_type', sa.String(length=64), nullable=True))
    op.drop_column('gem', 'assigned_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gem', sa.Column('assigned_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('gem', 'assignation_type')
    # ### end Alembic commands ###
