"""gem table 25

Revision ID: d49b5f45cf56
Revises: 13945cbac71d
Create Date: 2019-05-26 18:16:58.951716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd49b5f45cf56'
down_revision = '13945cbac71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nomination')
    op.add_column('gem', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.add_column('gem', sa.Column('master_id', sa.Integer(), nullable=True))
    op.add_column('gem', sa.Column('nomination_date', sa.DateTime(), nullable=True))
    op.add_column('gem', sa.Column('nomination_type', sa.String(length=64), nullable=True))
    op.alter_column('gem', 'type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_foreign_key(None, 'gem', 'user', ['master_id'], ['id'])
    op.alter_column('preference', 'gem_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'character',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'character',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('preference', 'gem_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'gem', type_='foreignkey')
    op.alter_column('gem', 'type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('gem', 'nomination_type')
    op.drop_column('gem', 'nomination_date')
    op.drop_column('gem', 'master_id')
    op.drop_column('gem', 'assigned_date')
    op.create_table('nomination',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('nomination_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assigned_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('elf_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['elf_id'], ['user.id'], name='nomination_elf_id_fkey'),
    sa.ForeignKeyConstraint(['gem_id'], ['gem.id'], name='nomination_gem_id_fkey'),
    sa.ForeignKeyConstraint(['master_id'], ['user.id'], name='nomination_master_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nomination_pkey')
    )
    # ### end Alembic commands ###
